### ISSUE TITLE
Emotions - creating the initial dataset of words

### ISSUE THREAD

**Issue by damirsaleschoice** [Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka#11]
Please provide a list of words that imply some kind of emotion.  For example, joy, grief, happiness, sadness, ...
The format is a text-only, delimited by space.

You can use any source you want, any dictionary, synonyms... any kind of a source or material you can think of.
On the other hand, you may need to research Internet if this has already been done for you, so you don't reinvent the wheel.

The more, the better!  why?
- simply because (otherwise) we will have to automatically search for more words, and this approach will have errors. These errors will have to be removed by hand, and it will be a very boring task to do.  Therefore, it is better if you can find the big list somewhere.
- we need the big list in order to get as much of a variety of sentences that deal with emotions, as possible. This way, our Artificial Intelligence model will represent the real world much closely.

**Comment by sherlockliang888** [comment]
Done
