### ISSUE TITLE
Select your tech-stack (front and back-end)

### ISSUE THREAD

**Issue by damirsaleschoice** [Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka#12]
Choose any tech-stack that you wish to use and learn. However, make sure that it can make the POST and GET (RESTful) call to API.  They will be making calls to a Java (Weka) engine that I will develop based on our diagrams and based on the algorithms that you chose. I will also fill-in the gap in knowledge that may exist.

KEEP IT SIMPLE!

We can use plain HTML and Javascript only to accomplish the main task, while keeping the data in some text-file.  I will be here to help you choose the tech-stack, however, feel free to choose anything that will complete the application and make the application presentable. Any stack you choose will be your own responsibility, so know your limits.  I will be here to guide you and help you overcome those limits.  Think about functional rather than what sounds cool and great. Most of the times, in the work environment, you will find a need to cut-the corners and simply make things work. Although we may disagree with such an approach, at the end, it is what makes the stakeholders happy, and what pays-off our rent.

**Comment by damirsaleschoice** [comment]
Can I call this "DONE" ?

**Comment by sherlockliang888** [comment]
Sure, done.
