### ISSUE TITLE
Download, Install Pencil - and make the mock page front-end design

### ISSUE THREAD

**Issue by damirsaleschoice** [Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka#20]
The purpose of this task is to decide which functions we will need for the Front-End before starting to code.
Please draw the mock-diagrams of the front-end design that the user will see once they access the page.
Mock diagrams can be something that people can draw on the paper, whiteboard, even the napkins!
The purpose is not to have something beautiful, but just to show and discuss the main idea and the objective.
Also, please draw any other pages that the users will see (usually happens after each REST call or after each diamond node from the work-flow diagram). Please follow the workflow diagram and use the Pencil software to draw all the changes that happen on the screen. Each change is a new mock-diagram ! HINT: Save your work and re-use the saved files.

Go to:
https://pencil.evolus.vn/Downloads.html
Download the version you want to use (Windows or .DEB for Linux, does not matter)
Install it, draw the images, save the images (as JPG or PNG) and upload them to this repository in a separate folder.

You can uninstall the Pencil software once this ticket is closed.

**Comment by damirsaleschoice** [comment]
SUBTASK:  When done, label each drawing you make with some unique ID (of your choice).
- Make a flowchart without using any words at all, just the IDs. Ignore the calls to REST API . To make it simple use start, end, rectangle and diamond nodes.
- Then, we will expand with the words and descriptions as well as the REST API calls.

**Comment by sherlockliang888** [comment]
Done
