### ISSUE TITLE
Investigate if George Brown would allow us to do the free web-hosting for our project

### ISSUE THREAD

**Issue by damirsaleschoice** [Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka#22]
Please find out, and let me know.
We will run Java with Jetty(server) and will need about 2-5GB of the free space, perhaps 2GB of RAM.
Apache server with HTML and JavaScript making the REST call to Jetty
Ubuntu instance

**Comment by sherlockliang888** [comment]
They don't allow students to request something of this nature. 

Done
