### ISSUE TITLE
Filter (clean) the emotion list 

### ISSUE THREAD

**Issue by sherlockliang888** [Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka#28]
There can be duplicates in the list, remove duplicates and save the file in the format we want (text-only, space/comma separated?).

**Comment by damirsaleschoice** [comment]
DONE:
https://github.com/Sales-Choice-Volunteering-Project/EmotionAnalyzerWeka/blob/main/misc/emotions/listOf.txt
